name: Bug report
description: Report a problem or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please include enough detail to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
      placeholder: Short summary of the issue.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps and commands.
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs or stack traces.
      render: shell
  - type: input
    id: version
    attributes:
      label: Version
      description: Git commit hash or release version.
      placeholder: e.g., 0.1.0 or 1a2b3c4
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: e.g., 3.10.13
  - type: input
    id: device
    attributes:
      label: Device / emulator
      description: Model, Android version, and whether it's a real device or emulator.
      placeholder: e.g., Pixel 6, Android 14, emulator
  - type: input
    id: run-mode
    attributes:
      label: Run mode
      description: Dry-run or real execution.
      placeholder: e.g., --dry-run 1
