name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please share context and desired behavior.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the pain point or limitation.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
      placeholder: Describe the desired behavior or API.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative approaches you considered?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or related issues.
